name: Deploy to Amazon ECS

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: MY_AWS_REGION                   # set this to your preferred AWS region, e.g. us-west-1

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ AKIAXNCC4M4FLEVHZV }}
        aws-secret-access-key: ${{nhVG5wasdsODcNilWyuK1opZV3mNMfgpPZCnQII7 }}
        aws-region: ${{ ap-south-1.compute.amazonaws.com }}
